# This is a basic workflow to help you get started with Actions

name: Deploy UI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch: {}
  push:
    branches: [ 'main' ]
    paths: [ './ui' ]

defaults:
  run:
    working-directory: ./ui
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  - build-ui:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: ui
          path: ./ui/build
  - deploy-ui:
    - uses: actions/download-artifact@v2.0.5
      with:
        name: ui
        path: build
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/cli@v1.0.0
      with:
        # Todo grab the storage name from the infra deploy somehow
        inlineScript: az storage blob upload-batch -d $web --account-name wormshostedfe7mmc3ngleqm -s build
