# This is a basic workflow to help you get started with Actions

name: Deploy Infrastructure

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths: [ "./infra" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-infra:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Bicep Build
        uses: aliencube/bicep-build-actions@v0.1
        with:
          files: infra/main.bicep
      - uses: azure/arm-deploy@v1
        with:
          subscriptionId: 1f148326-9562-4384-8ad6-6055c876c2e8
          resourceGroupName: worms-hosted
          template: ./infra/main.json
          deploymentMode: Complete
